### ISSUE TITLE
Error: Could not find or load main class ScrapeUserGUI

### ISSUE THREAD

**Issue by JohnBakery** [jayden2013/PhotobucketMiner#1]
When I run `java -classpath .;jsoup-1.8.3.jar ScrapeUserGUI` under Windows 10, I get the following error

Error: Could not find or load main class ScrapeUserGUI
Caused by: java.lang.ClassNotFoundException: ScrapeUserGUI

**Comment by jayden2013** [comment]
First run `javac -classpath .;jsoup-1.8.3.jar ScrapeUserGUI.java`, then run `java -classpath .;jsoup-1.8.3.jar ScrapeUserGUI`.
